name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name : Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Compilation debug
        run: ./gradlew assembleDebug

      - name: run tests unit
        run: ./gradlew testDebugUnitTest

      - name: Analyse statique
        run: ./gradlew lintDebug

      - name: save reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Reports-Tests-Android
          path: |
            app/build/reports/
            app/build/test-results/

      - name: Cache SonarQube
        uses : actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Envoyer l'analyse à SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info -Dsonar.qualitygate.wait=true
